language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: kN/NjWJyx4GVD/FJLLNxhRfsMz0iCt7afYQunImOtUgMHI175uzqZvTHCiKyyL6Z4Qv4wqog0jWdGtbB8Zc4P4fLugKQG/B8S5hjpiMoek6fLFVUgY0n3WUC+pIDZxYPB4hLydZcOTsGJjTulaf1xhr4azIftozqC2x4qNx8Vpy4X71/9gRd6c0dyRwkD/I8lv2Wb78qIn8wFsP57NjlekbmBIype898aLNO8+UqqSY2xTXJs17WYjk3k6UeGss3EPBN8jeYnOVY4pie2cHXoZC3RdK2s34DSpToknDCtAtfj+BA1iYG0ARfv8jUcHc2umwDBE3wrb6kMc6MBg5MOjRBY290KwgzJAMAWWOOP7BUGCaEL2SCJ4lpIhsXeUAPC4Ar+ZTaBbitAxvz7zTfUSmKGwc8In3LhzCgohboKW5v5he9V8L3/yrBF5v+/JwHnlrKxVEA3Xe/iHxSJ3FFSKZTJe2qUk8pbeNVmYQBuNyM6cBzfikQnJ/UzfQX1u5ixnxqelRT6/JCwkYXUuoLM01LHab0mnbQlYoEtLmE/XnImpCHGC/ym2lY4A5uM8L3k6F+DPACVOUqhGdACAFwvjB98MJ54UHz7hcMyYyIGBeIPar/H4/RQjoVg0VNSV2taPY6AIS2XC2fgaulVYMXscGSHIz37xipkqjCjTv/qRY=
  - secure: dTdsolsoSjNBBS1aOfz22HI/JsZ/pqVeaV/CdhtKoSRJLoki8utF8f2ld/Bmg5FjJFEwOt78SV2ORYXg45lPt/JnQEv4R4bInTHhxB7NcqIp1DuBOkbUzjePNwViP3mZ7qCM7rjJFhvIIi0Qlpuc2mL42JqdImBmo2y2wIgTCoF/PE+JHxw/pJm0Rwo7wp0gHnW8YJXch51Mc4rxjXKYE1MbAPX581vv4O5zsnZ4tE1u8dGl4BOb0pJTV6LB6YVMDMwCV9RPRcDR4hBpSOFteAiBODV0dPwRPzyv3EYetWkiCP7VATJVc361qgsrdGlh07xVFWqBelPdq45uNwsvP41hAa/E6AUxQN4odxXb26e7Ua5ljZxRwMXSZTMX5okBjpPkgNRc4U77KM4aQrgVoKgerDI537515C7eg9jHKnBpH/z6RZyjpbxRwTNYha5jx6bmvxvkW0wTHK9B8w0qcZVv2Ve89ejW2F31fMmLQGREpqBa7Dsxy9sB8pSkSfPaISNjBguA233L3AX9+oNRlc3aQVOumNuZWv41TtUhMX3zMPRDWZmxnHZEMw1g1qAD4vj4FioKe6EW663rxlJF/zmtMv8T8c9EhkOzimu9z/lNefqgjXoyzFfIiq09FGQcmOnLJHAfm/kqND9JTg1O8v9uqz/cp+KSlxxC5wkR7cI=
